### ISSUE TITLE
How to use Label Dectection for multiple images?

### ISSUE THREAD

**Issue by brucehieu96** [ThijsFeryn/google-cloud-vision-api#2]
Hello, sr for the wrong place that i asked u 'cause i've just used GitHub for a few days!
After seeing your hint in the old place, i'm still not understand what you mean and how to do it! Can you describe more details? I mean i'll use the loop for each image with the label dectection feature, is it right?

**Comment by ThijsFeryn** [comment]
Hi, 

Here's an example on how to load multiple images from the filesystem and process them using label detection:

```php
<?php
require dirname(__DIR__).'/vendor/autoload.php';
$api = new GoogleCloudVision\Api(getenv('apiKey'));
foreach (new DirectoryIterator(dirname(__FILE__).'/img') as $fileInfo) {
    if($fileInfo->isDot()
        || !$fileInfo->isFile()
        || !preg_match('/^(jpg|png)$/',$fileInfo->getExtension()))
            continue;
    $api->addImageByFilename($fileInfo->getPathname());
}
$api->addFeature($api::FEATURE_LABEL_DETECTION,10);
$result = $api->request();

foreach($result as $key=>$value) {
  var_dump($key,$value);
}
```

The script assumes that there is an `img` folder in the current directory containing either `jpg` or `png` files that need to be processed. I'm using a `DirectoryIterator` to scan the `img` folder for images.

You could also refactor this script and load the data via a collection of URLs as well.

Hope this helps!

**Comment by brucehieu96** [comment]
Thank you so so much! I extremely appriciate this!

**Comment by ThijsFeryn** [comment]
No worries, glad I could help.

**Comment by brucehieu96** [comment]
'Cause i'm doing the Final Project like Instagram, but i wanna give something differences, so i wanna add google vision to my project to get the tags of each image automatically. Thanks to your api library, i can solve 70% my problem!
